# Generated by Django 3.0.1 on 2020-01-05 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tempatParkir',
            fields=[
                ('id_parkir', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('kosong', 'Kosong'), ('booking', 'Booking')], default='kosong', max_length=50)),
                ('position', models.IntegerField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
