# Generated by Django 3.0.1 on 2020-01-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempatparkir',
            name='delayposition',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempatparkir',
            name='delayposition1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempatparkir',
            name='position1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
