# Generated by Django 3.0.1 on 2020-01-07 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkir', '0002_auto_20200105_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('parkir', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='parkir.tempatParkir')),
            ],
        ),
    ]
