# Generated by Django 3.0.1 on 2020-01-09 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkir', '0008_auto_20200107_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempatparkir',
            name='delayposition1',
        ),
        migrations.RemoveField(
            model_name='tempatparkir',
            name='position1',
        ),
        migrations.AlterField(
            model_name='booking',
            name='parkir',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='parkir.tempatParkir'),
        ),
    ]
