# Generated by Django 3.0.1 on 2020-01-09 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkir', '0009_auto_20200109_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnParkir',
            fields=[
                ('id_on_parkir', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('delayposition', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='parkir',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='parkir.tempatParkir'),
        ),
    ]
