# Generated by Django 3.0.1 on 2020-01-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkir', '0010_auto_20200109_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onparkir',
            name='backdelayposition',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onparkir',
            name='backposition',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onparkir',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempatparkir',
            name='backdelayposition',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempatparkir',
            name='backposition',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
