# Generated by Django 3.0.1 on 2020-01-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkir', '0011_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempatparkir',
            name='backdelayposition',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempatparkir',
            name='backposition',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
